### ISSUE TITLE
Add support for `react-jsx` in `tsconfig.json` `compilerOptions` -- upgrade to TS v4.1

### ISSUE THREAD

**Issue by pradella** [jaredpalmer/tsdx#1073]
Hi everyone

Sharing my workaround for those who are struggling to fix compiler errors when using `react-jsx` in your  `tsconfig.json`.

In my case, the error was: `'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts(2686)`.

Solution: in `tsconfig.json`, change `react-jsx` to `preserve`, as [replied in another issue](https://github.com/formium/tsdx/issues/710#issuecomment-624413332): 

```
// in tsconfig.json, change "react-jsx" to "preserve"
{
  "compilerOptions": {
    ...
    "jsx": "preserve"
    ...
  },
}
```

If possible in a near future, add support for `react-jsx`.

**Comment by agilgur5** [comment]
`react-jsx` is only supported by [TS 4.1+](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#typescript), so this is due to TSDX using TS v3.

As such this is duplicative of #926 , and the workarounds using Yarn `resolutions` or (NPM `overrides`) there to upgrade TS will work to enable `react-jsx` as well.

> Sharing my workaround for those who are struggling to fix compiler errors when using `react-jsx` in your `tsconfig.json`.

Appreciate you sharing another workaround in the meantime though for other users who were stuck!
