### ISSUE TITLE
Provide easy customization for the PORT NUMBER in development mode

### ISSUE THREAD

**Issue by bk973** [jaredpalmer/tsdx#1084]
I don't know if this feature is available yet. I read through the DOCs but I couldn't find any guides on how to change the port number of the development server.

**Comment by agilgur5** [comment]
Sounds like a possible duplicate of #780 -- TSDX has no server component and therefore no port.

If you're talking about the _example_ that's provided in the templates, that uses Parcel, not TSDX, so you can find that in [Parcel's docs](https://parceljs.org/features/development/#dev-server).

It's hard to tell what the intent of this issue was though, since the entire issue template was removed and no context was given.
