### ISSUE TITLE
Polyfills are not generated from .browserslistrc queries

### ISSUE THREAD

**Issue by ekb1zh** [jaredpalmer/tsdx#1132]
My algorithm:

```sh
npx tsdx create mylib # run create new project and select "basic" option
```

```sh
cd mylib # go inside project
```

```sh
npm i # install packages
```

```sh
touch .browserslistrc # create file .browserslistrc
```

```sh
echo "dead" >> .browserslistrc # append query "dead" into .browserslistrc
```

```sh
> src/index.ts # clear src/index.ts
```

```sh
echo "export default () => { console.log(Object.fromEntries([[\"a\", 1]]), Promise.resolve(0)); }" >> src/index.ts # append code into src/index.ts
```

```sh
rm -r test # remove test folder with old code
```

```sh
npm run build # build project
```

```sh
cat dist/mylib.cjs.production.min.js # see result
```

Result - polyfills are absent. But they are need for execute code in `dead` browsers ))

These questions have been discussed in these threads `.browserslistrc` https://github.com/jaredpalmer/tsdx/issues/951, `Object.fromEntries` https://github.com/jaredpalmer/tsdx/issues/968, `tslib` https://github.com/jaredpalmer/tsdx/issues/412, but I didn't find an answer to the question - if targeting `.browserslist` file to the old browsers, should TSDX add polyfills?
* If yes, then this is not the case now.
* If not, so how would such code work in older browsers?

> Note:
> If an incorrect request is entered into the .browserslist file, then an error will appear during the build, which means this file is included in the build, but why are polyfills not generated.

**Comment by agilgur5** [comment]
> * If not, so how would such code work in older browsers?

Per https://github.com/jaredpalmer/tsdx/issues/968#issuecomment-791817207 , polyfills are currently out-of-scope for TSDX. They were planned per that answer but were never a part of TSDX outside of regenerator/async/await. That answer also mentions how polyfills in libraries are still a topic of discussion in the JS community.
Adding the `.browserslistrc` as such will effectively tell `@babel/preset-env` to _transform_ your code to as old as possible, but it won't insert polyfills for behavior that can't be transpiled down to an earlier environment.

The suggested solution in https://github.com/jaredpalmer/tsdx/issues/968#issuecomment-791817207 is still the suggested solution in this case, that would make `corejs` polyfills added. `usage-pure` means it won't pollute the consumer environment and many consumers already have `corejs` installed anyway, so that is my suggestion.
(Side note: `babel-polyfills` is also now a very stable collection of packages and is actually used under-the-hood of `preset-env` nowadays. I've also contributed a good bit to it)
