### ISSUE TITLE
Support Rollup input extension .jsx

### ISSUE THREAD

**Issue by sisp** [jaredpalmer/tsdx#143]
### Current Behavior

The file `src/index.jsx` is not recognized as a Rollup input:

https://github.com/palmerhq/tsdx/blob/943648edb06cd131f2c1751120cd1301804b480b/src/index.ts#L64-L69

### Expected behavior

It should be possible to have the file `src/index.jsx` as the Rollup input.

### Suggested solution(s)

```ts
async function jsOrTs(filename: string) {
  const extension = (await isFile(resolveApp(filename + '.ts')))
    ? '.ts'
    : (await isFile(resolveApp(filename + '.tsx')))
    ? '.tsx'
    : (await isFile(resolveApp(filename + '.jsx')))
    ? '.jsx'
    : '.js';

  return resolveApp(`${filename}${extension}`);
}
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.6.1
| TypeScript       | 3.5.1
| Browser          | Chromium
| npm/Yarn         | npm
| Operating System | Ubuntu 18.04

**Comment by sisp** [comment]
Related to the this issue, TSDX currently does not seem to support importing `*.js(x)` files from `*.ts(x)` files because `rollup-plugin-typescript2` is not configured to process `*.js(x)` files.

https://github.com/palmerhq/tsdx/blob/943648edb06cd131f2c1751120cd1301804b480b/src/createRollupConfig.ts#L146-L162

The fixed configuration looks like this:

```ts
typescript({
  // everything from above, plus ...
  include: ['*.(t|j)s+(|x)', '**/*.(t|j)s+(|x)'] // default is ["*.ts+(|x)", "**/*.ts+(|x)"]
})
```

**Comment by sw-yx** [comment]
tsdx is quite evidently a typescript-first project. not a priority for me to support .js{x} but lets see what jared says

**Comment by sisp** [comment]
That's true, but I was thinking to align tsdx's features with CRA and CRA with `--typescript` set also resolves .js{x} files.

**Comment by agilgur5** [comment]
I'm not having this issue, but I think if `tsdx` supports `.js` it should also support `.jsx`. That would also add better support for gradual migrations to TS.

**Comment by myklt** [comment]
Isn't the problem here that Typescript doesn't support `.jsx` as a file extension for files containing jsx? As far as I know only `.tsx` is supported. More details: https://github.com/Microsoft/TypeScript/issues/30503

**Comment by agilgur5** [comment]
Wanted to update folks on this issue as this was discussed in #443 as well and I've made a few related PRs to improve JSX support.

Per #443, TSDX actually already supports JSX, you just need to make sure your `tsconfig.json` has `compilerOptions.allowJs` set to `true` and that your `include` picks it up. TSDX does not _by default_ allow JS or JSX but does support them _when they are configured_.

> Isn't the problem here that Typescript doesn't support `.jsx` as a file extension for files containing jsx? As far as I know only `.tsx` is supported. More details: [microsoft/TypeScript#30503](https://github.com/microsoft/TypeScript/issues/30503)

I'm not sure if this is the case or is still the case, but it works in TSDX. That might only be because TSDX runs Babel on top of `rollup-plugin-typescript2`, but I'm not really sure

There were some bugs related to JSX support, but those might not necessarily have caused issues for all JSX users. Related fixes:
#473 fixes an issue where custom Babel presets (like `@babel/preset-react`) weren't always properly merged with TSDX defaults
#474 fixes the specific issue here in the OP, JSX extensions for entry files, with OP's suggested solution
