### ISSUE TITLE
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor

### ISSUE THREAD

**Issue by Meemaw** [jaredpalmer/tsdx#170]
### Current Behavior

cjs loader crash:

<img width="1202" alt="Screenshot 2019-07-29 at 08 51 48" src="https://user-images.githubusercontent.com/8524109/62027568-46c9d800-b1de-11e9-9a95-cb1ddca854b7.png">

### Expected behavior

Things should work -- they worked on tsdx version `0.5.8`

This happens after upgrading tsdx from `0.5.8` to `0.7.2`. CJS loader complains super() is not being called even though it is.

The package is also on NPM so you can install it and see the problem for yourself: https://www.npmjs.com/package/@meshwatch/backend-core

"Problematic class constructor":

<img width="625" alt="Screenshot 2019-07-29 at 08 55 05" src="https://user-images.githubusercontent.com/8524109/62027730-bdff6c00-b1de-11e9-8c51-f0c005743539.png">

Build command: `"build": "tsdx build --target node --entry src/index.ts"`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.7.2
| TypeScript       | 3.5.3
| npm/Yarn         | Yarn

**Comment by agilgur5** [comment]
Sorry this never got responded to. I'm a new maintainer as of earlier this month and have gone through most of the old issues and just got to this.

Not sure if you've fixed this since then but I can't reproduce this without source code (the repo linked in that NPM project seems to be private or no longer existent as it 404s for me), and a minimal reproduction would be much better.

I looked at your current package's [CJS on UNPKG](https://unpkg.com/browse/@meshwatch/backend-core@1.15.14/dist/meshwatchbackend-core.cjs.development.js) and the `UserService`'s constructor had `super()` first, so didn't seem to be a problem.
I also tried running it and it worked fine for me:
```bash
$ node
Welcome to Node.js v12.16.1.
Type ".help" for more information.
> const core = require('@meshwatch/backend-core')
undefined
> new core.UserService()
UserService {
  errorServiceResponse: [Function],
  serviceResponseFromBoom: [Function],
  serviceResponse: [Function],
  tryExecute: [AsyncFunction],
  getUserInfo: [Function],
  completeGettingStartedTask: [AsyncFunction],
  datasource: DynamoUserDatasource {
    createTable: [Function],
    getUserInfo: [Function],
    completeGettingStartedTask: [Function],
    insertUserInfoRow: [Function],
    userInfoFromDynamoRow: [Function],
    dynamoClient: DynamoDBTableClient {
      tableName: 'monitoring',
      dynamoDbClient: [DynamoDBClient]
    }
  }
```

But it looks like that was [built with v0.5.8](https://unpkg.com/browse/@meshwatch/backend-core@1.15.14/package.json), so I have no idea what it looks like with a different version without the source and don't have a way to test.

It might've been a transform bug in a Babel plugin somewhere, not sure. TSDX has been updated a lot since then, so if it doesn't work with v0.13 we can reopen this when given a minimal repro.
