### ISSUE TITLE
Option to opt-out of eslint-plugin-react

### ISSUE THREAD

**Issue by zcuric** [jaredpalmer/tsdx#279]
### Current Behavior

`tsdx` supports `eslint-plugin-react` outof the box. If React is not used this warning pops up: 
```
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
```

### Desired Behavior

Opt-out of `eslint` plugins that are not in used. For example, I'm using `tsdx` to build a logger plugin for a specific library. I don't need `.eslintrc` extending`react-app`, because my work is only `node` related. 

### Suggested Solution

My suggestion is to remove any dedicated `eslint` plugin except the ones that are `typescript` and `prettier` related. User would manually add additional rules to the project if needed, for example `eslint-plugin-vue`, and configure it in the local `.eslintrc`.  This way `tsdx` remains decoupled from any specific library.

### Who does this impact? Who is this for?

TypeScript users that develop plugins, libraries for NodeJS.

**Comment by arthurdenner** [comment]
@zcuric, I looked into this and noticed that, in order to remove the warning thrown by [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react/blob/61c79716e6d18cf07997eab3bd6b27941c7e8d3a/lib/util/version.js#L24), we would need to change `tsdx` quite a lot because there is no way to ignore this message on the plugin that `react-app` is using it under the hood.

And also, we can't remove `react-app` from the `extends` list if the project doesn't have `react` as a (dev)dependency because that would cause other issues since it handles a lot more stuff - like TypeScript parsing.

If @jaredpalmer is on board with this, I'd like to work on a change, but I'm not sure if it's worth. The warning is harmless anyway.

**Comment by zcuric** [comment]
@arthurdenner `tsdx` is great tool and I know that authors are very tie to React ecosystem, but my reasoning is to to make the tool better is to decouple it from any specific framework and provide the basis to develop any kind of TS library, regardless of environment. Not just removing specific `eslint` plugins, but all that specific coupled stuff. 

Sadly, I'm not experienced in TS that much for a proper contribution to the project, but from what I see, this could be done.

**Comment by arthurdenner** [comment]
@zcuric, as I said, it definitely can be done. If you want to work on it, you just have to change the ESLint config that is [created](https://github.com/jaredpalmer/tsdx/blob/master/src/createEslintConfig.ts) on the `lint` command. My point was that we are currently using a tool that handles more than just React, so removing it requires more changes and I'll wait for some input from maintainers to suggest some changes.

**Comment by JustFly1984** [comment]
As I understand, react-app is part of dependencies for templates. I think if you move ./src to sub directory and manage dependencies for project in separate package.json from templates, you can get rid of stuff which is not directly required by tsdx itself.

**Comment by sw-yx** [comment]
@arthurdenner i'd be happy to accept a PR for this
