### ISSUE TITLE
Problem with target = CommonJS in tsconfig

### ISSUE THREAD

**Issue by wiput1999** [jaredpalmer/tsdx#345]
### Current Behavior

I'm about to use tsdx to build library for Node.js but it still need to add .default after require. So I'm tried to change to `export = ` and tsconfig target to CommonJS then 

```
Module resolves to 'CommonJS'. This is incompatible with rollup, please use 'module: "ES2015"' or 'module: "ESNext"'.
```

is it possible to solve this issue?

### Who does this impact? Who is this for?

Who using `export = ` and target as commonjs

**Comment by sw-yx** [comment]
not sure. if you can investigate and propose a fix, please let me know

**Comment by wiput1999** [comment]
In my opinion but not sure I think it’s problem from rollup. Maybe next week if I’ve time I’ll try looking about this

**Comment by hardfist** [comment]
I think the problem is that tsdx use 'named' exports rather than  'auto' exports(which is rollup's default behavior ), which I think auto is more appropriate for the ugly `export default` things,
the difference between auto mode and named mode is different when treating `export default`
```
export default 42;
```
auto mode generates
```
'use strict';

var main = 10;

module.exports = main;
```
named mode generates
```
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var main = 10;

exports.default = main;
```
and auto mode works perfectly with node && browser
```
const lib = require('lib') // ok
```
```
import lib from 'lib' // ok when set esmoduleInterop: true
```
@sw-yx @jaredpalmer

**Comment by SokratisVidros** [comment]
I also came across the same issue while building a Node library. Is there a suggested `tsconfig.json` setup that eliminates the need of `.default` in CommonJS imports?
