### ISSUE TITLE
Allow disable output dist/index file

### ISSUE THREAD

**Issue by zhaoyao91** [jaredpalmer/tsdx#382]
### Current Behavior

I have customized the `tsdx.config.js` as such

```
// Not transpiled with TypeScript or Babel, so use plain Es6/Node.js!
module.exports = {
  // This function will run for each entry/format/env combination
  rollup(config, options) {
    config.preserveModules = true;
    config.output.file = undefined;
    config.output.dir = `${__dirname}/${config.output.format}`;
    console.log(config);
    return config; // always return a config.
  },
};
```

Hope it to generate files that match the structure of sources in `${format}` dir .

However, there always is a `dist/index.js` file, which is not desired.

### Desired Behavior

Only `esm` and `cjs` dirs are generated, no `dist` dir.

### Suggested Solution

Support some customization to allow the pattern of keeping the structure of source files.

### Who does this impact? Who is this for?

?

### Describe alternatives you've considered

As `cjs` is not for the future, I may disable generating cjs modules to workaround it for some time. But it is not perfect.

**Comment by agilgur5** [comment]
`dist/index.js` (or something like it) is necessary for determining whether to use dev or prod CJS builds. It is exclusively for CJS, so if you disable CJS, it won't be produced. With multi-entry or `preserveModules`, it only gets created once though, whereas it should be created for _each_ CJS module.

With #367 you can do something like `tsdx build --entry src/**/*.ts` and that will create one for each CJS module, but it's not the same as `preserveModules` as it creates separate bundles for each file. Might be able to add `preserveModules` _on top of_ the changes in #367 and that might work, but I'm not really sure.

Related to  #367, #175 , #276 , #299, and #321 . I believe the example here improves on my workaround for #321 as well (though I haven't tested it). Based on all the issues, seems like TSDX should have better support for multi-entry _and_ `preserveModules`, which are related and may use similar code to achieve, but are not the same.

**Comment by agilgur5** [comment]
So as I mentioned in https://github.com/jaredpalmer/tsdx/issues/276#issuecomment-615901358 , the use of `--preserveModules` for CJS causes some issues and I'm not sure it provides any tree-shaking benefits (because it's CJS) either.

It's also not meant for creating multiple entries, there is a separate feature for that that is leveraged by #367, and #367 handles creating the dev/prod switch for each entry too.

Going to close this as won't fix because there isn't really a need to disable creating `dist/index.js` and it is _necessary_ to be able to switch between dev/prod CJS. If you're not using CJS, you don't need to switch between dev/prod CJS, and it won't be generated already.

Please see https://github.com/jaredpalmer/tsdx/issues/276#issuecomment-616200604 for a better config for `preserveModules` for ESM.
