### ISSUE TITLE
Opt-in tsdx analytics / telemetry

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/tsdx#392]
I want to understand usage in more depth and want to add the option to opt-in analytics / telemetry in the cli when folks bootstrap a new project. 

Questions I want answers to:
- Total / avg / median build time against various dimensions
- Most popular deps 
- CLI flag usage
- Module format popularity
- Installed TypeScript version
- Installed TSDX version
- Number of files 
- Number of test files
- TypeScript error numbers (maybe)
- Bundle size
- Template popularity

No I don’t want to read anyone’s code, just get some anonymous metadata that can inform us and everyone about directional usage trends. I will open source all aspects of the tracking code and backend. 

**Proposed Infrastructure**
Since it’s probably too controversial to use google analytics, we will roll it on our own. Luckily, this isn’t as bad as it sounds. Inside of the codebase, we just make a lil analytics client that sends simple GET requests with data as a query string to an AWS Cloudfront distro. We can then use S3 and Athena to transform the logs into usable metrics. We can the. embed stats on the future tsdx website I’m never going to finish 😉. We can also potentially use cube.js to make generating the react charts even easier.

Some possible architectures:
![](https://d2908q01vomqb2.cloudfront.net/b6692ea5df920cad691c20319a6fffd7a4a766b8/2019/02/01/ClickstreamSessionsKinesisGlueAthena3.png)

Or a simpler one: 
![](https://cloudonaut.io/images/2019/04/athena-quicksight.png)

(If we wanted to be cool AF, v2 could give folks the ability to see their own stats (wouldn’t be anonymous though))

**Alternatives**
- We can debate the merits of allowing some analytics company to “donate” the analytics (e.g Mixpanel or Keen.io). However, my guess is that our little analytics solution, abstracted on its own, would be a fairly popular project in and of itself.

**Discussion**
- How do people feel about this? 
- We can’t give everyone access to the AWS account but maybe there is a way to make the raw data publicly available

**Comment by jaredpalmer** [comment]
AWS blog about how to implement this architecture: https://aws.amazon.com/blogs/big-data/create-real-time-clickstream-sessions-and-run-analytics-with-amazon-kinesis-data-analytics-aws-glue-and-amazon-athena/

**Comment by jaredpalmer** [comment]
Got Athena working without a single line of code. Kinda cool

**Comment by agilgur5** [comment]
Some comments:
1. To better inform decisions, it's certainly a good idea. And I think opt-in is the right way to go and open-sourcing would be a must. There are some caveats with this though:
    1. Opt-in inherently biases the data to reflect power users / supporters / contributors. That's likely to not be representative. It would still be a data point, but taken with a grain of salt.
    1. Data will also be skewed by the largest users. This can be controlled for in analysis, but may require pseudo-anonimity (e.g. hashed IDs or GUIDs). Pseudo-anonimity could be used to let folks find themselves (have the CLI be able to display your hashed IDs)
2. To make the data public, can make the bucket read permissions open to everyone (but restrict write to the events pipeline). You would be charged for public read/download events however.
AWS also has a [Public Dataset Program](https://aws.amazon.com/opendata/public-datasets/) and GCP has [Public Datasets](https://cloud.google.com/bigquery/public-data/) as well (I'm sure Azure does too, but I haven't used Azure). A notable example is the [PyPI download stats dataset on GCP/BigQuery](https://bigquery.cloud.google.com/dataset/the-psf:pypi)
3. There is a project that does something similar, albeit for a different purpose (OSS financing): [`scarf`](https://github.com/aviaviavi/scarf)
4. Would definitely recommend [`pulumi`](https://github.com/pulumi/pulumi) for Infrastructure-as-Code, particularly as it has first-class TypeScript support (and more generally is an IaC provider that uses actual programming languages instead of config files). I could volunteer some time to create the Pulumi configuration for a set-up etc (I'm also an infrastructure engineer). 
5. Can also look at various existing OSS solutions for different pieces of this. E.g. [Metabase](https://github.com/metabase/metabase), [Superset](https://github.com/apache/incubator-superset), [Franchise](https://github.com/HVF/franchise) are some popular tools for analysis + visualization that all have different complexity / features / integrations.
6. As with all self-hosted set-ups, the real costs are in *maintenance* (including paging rotations), not so much in initial config. The simpler and the more managed services, the less this is a problem, but nonetheless a big consideration.

**Comment by jaredpalmer** [comment]
Update: I have a working proof of concept with Cloudfront logging to an s3 bucket plus Athena. Not even sure QuickSight is worth it since I can just download the Athena query by csv.

<img width="1012" alt="Screenshot 2019-12-25 08 32 32" src="https://user-images.githubusercontent.com/4060187/71446443-6adc0780-26f1-11ea-856d-c98411c06ada.png">
