### ISSUE TITLE
'npm link' not working ?

### ISSUE THREAD

**Issue by sovanjana** [jaredpalmer/tsdx#394]
as **npm link** not working, every time I am publishing the package to check a minimal changes.
am I the only person facing this problem ?
please help me to fix this issue . .

**Comment by zanonnicola** [comment]
I think it would be helpful to have a bit more context or a reproducible case/repo.
It's a bit hard to help otherwise.

Thanks!

**Comment by hidat** [comment]
So I ran into this on my development machine running Windows 10/npm 6.4.1.  The root of the evil appears to be if your library (lets call it 'new-library') depends on another library via 'npm link some-library'.  When you run 'npm link' for 'new-library', the existing link to 'some-library' gets destroyed, and the library does not compile.  
I hacked around this by:
 * Removing the 'prepare' script from the package.json
 * Making 'some-library' a peer dependancy of 'new-library' (not sure if this was actually needed)
After this, npm link would run without destroying the link to 'some-library'.  Just make sure that 'new-library' is built, and it should work.

**Comment by agilgur5** [comment]
TSDX doesn't touch any internals like `npm link`, so whatever the issue is here (no repro), it's unrelated to TSDX.

I've also personally used `npm link` with libraries written in TSDX with no issues and as have other users.

> I hacked around this by:

I haven't had this problem so I can't really comment, don't quite know what the problem is there. Just for reference, I don't normally use a `prepare` script and peer deps are the way Lerna works as well for monorepos.
