### ISSUE TITLE
Upgrading from TSDX 0.10 to 0.12 increases size by 0.12MB

### ISSUE THREAD

**Issue by daraclare** [jaredpalmer/tsdx#442]
### Current Behavior
This may not be a bug, if not, I apologise, but maybe documentation around this would be useful. 

After updating our package from version `0.10.x` to version `0.12.x` of TSDX, I noticed an increase of 0.12MB in our unpacked size in the NPM registry. I realise this maybe because of the addition of our components folder, I assume this enables importing of individual components. How would we use this to our benefit, and is there a flag to turn this off if we decide not to use it?

**PACKAGE DETAILS @ TSDX v0.12.x**
<img width="1000" alt="Screenshot 2020-01-22 at 14 08 16" src="https://user-images.githubusercontent.com/5235711/72973570-66287300-3dc5-11ea-9f3e-f48ba67350b3.png">

**PACKAGE DETAILS @ TSDX v0.10.x**
<img width="1000" alt="Screenshot 2020-01-22 at 14 07 35" src="https://user-images.githubusercontent.com/5235711/72973583-6cb6ea80-3dc5-11ea-945d-122a4878f08f.png">

NOTE: we reverted the change to see if any other package had been bumped to a minor version which may have affected the change and the resulting package size was 0.01MB difference.

### Expected behavior
Although I wasn't expected it, this may be expected behaviour. Is there anything we should do to mitigate or improve this.

### Suggested solution(s)
Documentation on this might be useful, happy to help if I can.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.12.3
| TypeScript       | 3.7.3
| Browser          | N/A
| Yarn         | 1.19.1
| Node             | v10.15.3
| Operating System | 10.15.2

**Comment by agilgur5** [comment]
I think you mixed up the headings for your images (first one says 1.93MB on 0.10 and second says 1.81MB on 0.12).

Per the changelog, 0.10 tried to use `@wessberg/rollup-plugin-ts`, which turned out to be buggy, and 0.11 rolled that back to use `rollup-plugin-typescript2`.
Can't tell exactly without seeing the actual files, but based on your description the difference is probably that all versions other than 0.10 produce type definitions (`.d.ts`) on a per file basis, whereas `@wessberg/rollup-plugin-ts` tries to bundle and treeshake them into one file (which `tsc` doesn't even do). That's probably the reason for the differences, but can't tell exactly without seeing the files.
See also #200 and #287 and related discussions about the two different plugins

**Comment by agilgur5** [comment]
@jaredpalmer think it would be good to deprecate the entire 0.10.x line due the bugs in it to avoid further confusion.

**Comment by jaredpalmer** [comment]
Agree

**Comment by jaredpalmer** [comment]
I have just deprecated all 0.10.x releases with the following message:

`TypeScript compilation is broken in 0.10.x releases. Please upgrade TSDX >= 0.11.x`
