### ISSUE TITLE
Esmodule options in rollup output is always undefined

### ISSUE THREAD

**Issue by etienne-dldc** [jaredpalmer/tsdx#469]
Hi,

While working on #468 I noticed [this line of code](https://github.com/jaredpalmer/tsdx/blob/master/src/createRollupConfig.ts#L92)

```js
esModule: tsconfigJSON ? tsconfigJSON.esModuleInterop : false,
```

But `esModuleInterop` is a compiler option so I guess it should be 

```js
esModule: Boolean(tsconfigJSON?.compilerOptions?.esModuleInterop)
```

I can create a PR to fix this I just want to be sure that I'm not missing something here...

**Comment by agilgur5** [comment]
Oh sh*t, you're right, that's actually my code from #327 😨 . We don't have automated tests for `tsconfig` properties (we should! for #468 too preferably), but I actually have a fork of TSDX I used specifically for this feature and it worked there.... 😖 🤔 🤔 

Let me take a look at it when I get the chance. This syntax is preferred though.

I'm also working on adding tests for custom babel config (c.f. #443 ); custom tsconfig is actually easier (no new dependencies).

**Comment by agilgur5** [comment]
Ok, dug into this and found some strange results. The library I initially wrote this fix/feature for does indeed have `Object.defineProperty(exports, '__esModule', { value: true });` in its `dist/` output, see  https://unpkg.com/mst-persist@0.1.3/dist/mst-persist.cjs.development.js. So does https://unpkg.com/jest-without-globals@0.0.2/dist/jest-without-globals.cjs.development.js. Both have `tsconfig.compilerOptions.esModuleInterop` set to `true`.

So did some further sleuthing and some testing and turns out `esModuleInterop` is actually almost always _true_ now 😅 😅. Or rather, `tsconfigJSON ? tsconfigJSON.esModuleInterop : false` always evaluates to `undefined` -- and [rollup has `output.esModule` set to `true` by default](https://rollupjs.org/guide/en/#outputesmodule). It'll only be set to `false` if there is no `tsconfig.json`.

So yea, a PR would fix this. I think a test should re-use the directory in #468 (which might take a bit to get merged as Jared will likely be the one to merge it), and then could do something like:

```javascript
const buildExports = require('../stage-build/dist/index.js');
expect(buildExports.__esModule).toBe(true);
```

**Comment by etienne-dldc** [comment]
OK, I'll wait for #468 to be merged then

**Comment by agilgur5** [comment]
👍 Do you think you can rename this issue in the meantime? Just to avoid any confusion

**Comment by agilgur5** [comment]
@etienne-dldc now that #468 is merged would you like to PR the fix to this? I can merge that in a lot faster myself now that I'm a collaborator

**Comment by etienne-dldc** [comment]
Sorry for the late response...

Thanks for taking care of this 😃

**Comment by agilgur5** [comment]
No worries, I just wanted to get all the tsconfig changes & tests done in one go
