### ISSUE TITLE
[Question] yarn build-storybook always generate typescript declaration file in src

### ISSUE THREAD

**Issue by xiaoyu-tamu** [jaredpalmer/tsdx#515]
yarn build-storebook will generate typescript declaration in src folder, is this expected behavior?

![image](https://user-images.githubusercontent.com/33362998/75114291-86dd2600-561a-11ea-9b21-1fe7ebe350ee.png)

To reproduce:

1. npx tsdx create test
2. cd test
3. yarn build-storebook

**Comment by agilgur5** [comment]
Hi @xiaoyu-tamu , sorry this didn't get responded to earlier, I've gone through nearly every issue since I became a maintainer last month (c.f. #512 ), but this was one I missed over as it required investigation.

You removed the issue template (please don't do that, it's there for a reason), so I don't know what version of TSDX you were on.

I tried this on the latest TSDX v0.13+ and was unable to reproduce this.

v0.13 significantly upgraded the Storybook template (c.f. #435 ) and uses the new configuration available in Storybook 5.3+, which is quite different from the old one. I'm not sure if this problem exists in v0.12.3 or below, but it doesn't seem to exist in latest TSDX. I'd highly recommend upgrading to latest TSDX.

**Comment by agilgur5** [comment]
Ok, seems like this indeed occurs with v0.12.3 and no longer occurs with v0.13+, which changes the config. So this was fixed by #435

**Comment by xiaoyu-tamu** [comment]
Sorry about removed the issue template.  Yeah, it works in v13.
