### ISSUE TITLE
Redundant compiler options

### ISSUE THREAD

**Issue by slikts** [jaredpalmer/tsdx#619]
There are a number of redundant compiler options in the current `tsconfig.json`, and it could be cleaned up or simplified by removing them.

`strict` already enables `noImplicitAny`, `noImplicitThis`, `alwaysStrict`, `strictNullChecks`, `strictFunctionTypes` and `strictPropertyInitialization`.

`noUnusedLocals` and `noUnusedParameters` overlap with the `@typescript-eslint/no-unused-vars` ESLint rule, which results in duplicate errors in the editor (after the user fixes [this notable issue](https://github.com/jaredpalmer/tsdx/issues/354)):

![image](https://user-images.githubusercontent.com/137872/76853468-fdee8e80-6855-11ea-9be6-bf9a92a281e7.png)

This means, for example, that using the Go to Next Problem or Go to Previous Problem in the editor require being used twice to move past the same error.

**Comment by agilgur5** [comment]
> `strict` already enables `noImplicitAny`, `noImplicitThis`, `alwaysStrict`, `strictNullChecks`, `strictFunctionTypes` and `strictPropertyInitialization`.

Yea I removed the `strict` redundancy in TSDX's own tsconfig in #475 , but not in the templates. I think because I assumed there was some reason for that? Idr, but I agree there shouldn't be redundant configs.

PR welcome to remove those.

> `noUnusedLocals` and `noUnusedParameters` overlap with the `@typescript-eslint/no-unused-vars` ESLint rule, which results in duplicate errors in the editor

Yea I see this myself but don't particularly find it that annoying.
I'm not sure that these should necessarily be removed by _default_ though, particularly as not everyone uses `tsdx lint` or has the same rules. I'd rather that be opt-out from one side (TS) or the other (ESLint) based on user preferences

**Comment by agilgur5** [comment]
I think we could add a comment above the `noUnused` checks saying, for instance, `// if using ESLint, these two checks may be redundant with @typescript-eslint/no-unused-vars, can disable in that case` or something
