### ISSUE TITLE
react library with scss modules support

### ISSUE THREAD

**Issue by daniele-zurico** [jaredpalmer/tsdx#63]
### Current Behavior
Is not possible to use it with scss and module

### Desired Behavior
Be able to use it as CRA 

scss file: helloWorld.module.scss

ts: import style from "./helloWorld.module.scss"

### Suggested Solution
Have a look on CRA and see how it works

### Who does this impact? Who is this for?
All the developer that want to create a library with multiple modules and have support of scss

**Comment by jaredpalmer** [comment]
I don’t use css modules, so I’m not familiar with what best practices are for including/excluding them in a 3rd party component that eventually gets consumed by something like CRA or Parcel that actually does css processing. For example, Reach UI, has a vanilla CSS file that you eventually import into your app. Again, I’m open to this, I just don’t understand how it should be done

cc @markdalgleish

**Comment by Guria** [comment]
Just a `css` support only, even without preprocessors and modules, opens an abyss of new questions.

Should import of `css` be kept in transformed files or they should just used to collect style dependencies to extract one `css` file and disappear in transformed result? The same about `scss`. Additionally it could be left untouched or transformed to `css` import.

What about variables / mixins? Should they evaluated on per file basis or should we [collect all dependencies](https://github.com/nathancahill/rollup-plugin-collect-sass#why) first? 

Another big question here is assets (fonts, images, svgs, ...) mentioned in css/scss files or.

**Comment by hedgerh** [comment]
I think this could probably be closed and rolled up (haha get it) into https://github.com/palmerhq/tsdx/issues/110

**Comment by sisp** [comment]
[`create-react-library`](https://github.com/transitive-bullshit/create-react-library) is using `rollup-plugin-postcss`:

https://github.com/transitive-bullshit/create-react-library/blob/3375f3844fa0198e3db7ef715bebc784399f3e40/template/typescript/rollup.config.js#L30-L32

Is there anything wrong with this approach?

**Comment by sisp** [comment]
> Just a `css` support only, even without preprocessors and modules, opens an abyss of new questions.
> 
> Should import of `css` be kept in transformed files or they should just used to collect style dependencies to extract one `css` file and disappear in transformed result? The same about `scss`. Additionally it could be left untouched or transformed to `css` import.
> 
> What about variables / mixins? Should they evaluated on per file basis or should we [collect all dependencies](https://github.com/nathancahill/rollup-plugin-collect-sass#why) first?
> 
> Another big question here is assets (fonts, images, svgs, ...) mentioned in css/scss files or.

I'd say in a React component library, everything should be self-contained after bundling. That's why I'd say all CSS should be treated as CSS modules, so there are no name conflicts with a consuming app or component library. With `inject === true`, `postcss` adds the function `styleInject` which injects the (processed) CSS as a `<style>` block in the `<head>` block when the library is loaded. I think SCSS should be transpiled to CSS so the component library can be used as is (self-contained).

Assets could be treated similar to how Create React App does it. SVGs are imported as React components using `svgr` and images could be Base64-encoded and inlined. Assets in CSS could be Base64-encoded to yield a self-contained component library. 

Other libraries like [`create-react-library`](https://github.com/transitive-bullshit/create-react-library) and [`microbundle`](https://github.com/developit/microbundle) are taking similar approaches from what I can see.

**Comment by sw-yx** [comment]
we've enabled customizable configs since this issue was open. please have a try. we still have other users interested in css modules that are reporting small issues.
