### ISSUE TITLE
[Question] Best practice/example on building for react-native and web

### ISSUE THREAD

**Issue by poteirard** [jaredpalmer/tsdx#647]
Hello,

First of all thanks for your amazing library ❤️ 

We have a monorepo and some of the libraries like "api clients" needs to be built for react native and also web. I suppose like both `node` and `web` targets

Is there a way to achieve that in tsdx?

Thanks

**Comment by agilgur5** [comment]
I'm not an expert in this as I haven't necessarily built for both targets, but if this isn't a component library, it shouldn't be much different from targeting web.

Some examples:
- I have a library [`mst-persist`](https://github.com/agilgur5/mst-persist) that's used often in RN contexts (I use it in RN too). There's some docs on `AsyncStorage` but otherwise works the same on web and RN.
- [`immer`](https://github.com/immerjs/immer) sets the `react-native` field in `package.json` to [its ESM build](https://github.com/immerjs/immer/blob/949960fce7360ebd9796f1d208c32cea3d71a76a/package.json#L11)

I think "api clients" should for the most part be fine with that approach, but RN's `fetch` handling can sometimes be different from the browser due to how the native implementation works.

If you're using Hermes or an older RN Android (< v0.59), then you may have some issues with the environment as it doesn't support things like Proxies for instance, so you'd want to make sure if you're compatible (Proxies have no polyfill, but for most ES6+ features, you'd just want to transpile down to ES5 by setting your `preset-env` config accordingly).
Immer [explicitly notes this in its installation docs](https://immerjs.github.io/immer/docs/installation#immer-on-older-javascript-environments)

For component libraries you'd probably want to use something like `react-native-web` or build two separate variants.

**Comment by alexluong** [comment]
I have the same question. Not really about "best practice" per se, but how to build a universal component library with React Native Web using TSDX and have 2 example folders: web and native.

Bonus point if Storybook is included.

I struggled with this from [react-with-storybook](https://github.com/jaredpalmer/tsdx/tree/master/templates/react-with-storybook) template for a couple of hours tonight but couldn't come up with anything satisfactory.

**Comment by agilgur5** [comment]
@alexluong I do think that's separate from OP's intro as they said for "building" and "API clients", not for examples and components (and doesn't mention RNW).

But to answer the question, you could probably make the current `example` dir `examples/web/` and add an `examples/react-native` dir that uses Expo. Alternatively could make them both with Expo since it has some support for web builds nowaday -- depends on what you think your consumers are more likely to use for web.

Regarding Storybook, there is [Storybook for React Native](https://storybook.js.org/docs/guides/guide-react-native/) that you'd probably want to use.

PR welcome to add either to the templates, as we've had a small bit of RN interest and RN is typically more complicated where template/example could be helpful.

**Comment by poteirard** [comment]
Thanks a lot @agilgur5 for the detailed explanation. I quite new in react-native as well so I didn't know about `"react-native": '/dist/esm.js'`. 

I did some tests and by default it gets the "main" field of the `package.json` if `react-native` is not present. Good to know :) Both bundles works fine in RN indeed.

Many thanks also for the links and resources.
