### ISSUE TITLE
TypeError: text.trimEnd is not a function

### ISSUE THREAD

**Issue by sagar-gavhane** [jaredpalmer/tsdx#653]
### Current Behavior

I don't have any idea about this error & the main reason behind this just wants to raise an issue against this issue.

This is a link to my open source project: https://github.com/sagar-gavhane/rahome

![image](https://user-images.githubusercontent.com/33308798/77854250-d1982200-7206-11ea-9ca8-e7685655aab5.png)

**Comment by agilgur5** [comment]
Please fill out the issue template and don't selectively skip sections...

`trimEnd` is a newer ECMAScript feature and is only supported on Node v10+, so it sounds like you're using EOL v8 or something. But you didn't fill that part of the issue template out...
Notably this isn't popping up from TSDX's version of Prettier because [we haven't updated to v2+](https://github.com/jaredpalmer/tsdx/pull/632), it's popping up from the version you added in yourself in your devDeps, which is v2+.

> the main reason behind this just wants to raise an issue against this issue.

Sorry, I have no idea what you meant by this
