### ISSUE TITLE
upgrade prettier to v2

### ISSUE THREAD

**Issue by zhaoyao91** [jaredpalmer/tsdx#657]
### Current Behavior

the current tsdx uses prettier v1.19

### Desired Behavior

upgrade prettier to v2

### Versions

- tsdx: 0.13.1

**Comment by agilgur5** [comment]
Please see #632. It's quite breaking and still getting bugs/patches, so TSDX will update at a later date.
v0.13.x will likely focus on template improvements and perhaps some minor changes, we'll see if this is ready by v0.14

**Comment by jneuendorf** [comment]
Fortunately, I found this issue. I am using private fields (TS 3.8.3 I believe) which prettier@v1 cannot parse. Therefore, the version of prettier somewhat relates to the TS version one can use (or at least to the set of useable language features). So this should be stated in the docs/README, shouldn't it?
According to the package.json the TS version is `typescript@^3.7.3`...

**Comment by agilgur5** [comment]
Sorry for delayed response, private fields actually cause some build-chain issues upstream per https://github.com/formium/tsdx/pull/679#issuecomment-631478298. I think we might be able to upgrade still according to some users, so that's may not be a blocker per se, but it blocks usage of the private fields feature.

**Comment by MMT-LD** [comment]
@agilgur5 Just wandered if this will be updated at any given point or do we have any timelines? Currently i get an error
`error  Parsing error: 'from' expected  prettier/prettier` when i use `export * as something from 'something'`. I know the workaround is to import then re-export but would be good if we could bump this to v2.

Thanks is advance 😄

**Comment by agilgur5** [comment]
@MMT-LD the PR this duplicates is scoped out for [v0.16.0](https://github.com/formium/tsdx/milestone/4) to go along with TS upgrades and ESLint upgrades etc since they all affect each other (one of the issues with an all-in-one library; massive API surface and easy breakage). I'm still not sure private fields are supported however, but I think otherwise it should work.
You can workaround this by adding a `resolution` too.

Going to lock this as it's a duplicate.

**Comment by MMT-LD** [comment]
@agilgur5 Thanks for updating me. Looking forward to that release 😉 . Thanks for maintaining such an awesome lib 👏
