### ISSUE TITLE
Spread transpilation issue with `Array` -- downlevelIteration usage?

### ISSUE THREAD

**Issue by ndrbrt** [jaredpalmer/tsdx#659]
### Current Behavior

Suppose we have this code:
```js
const A: Array<number> = [
    ...[...Array(10)].map(() => 0),
    ...[...Array(5)].map(() => 1)
]

const B: Array<number> = []
for (let i = 0; i < 10; i++) {
    B.push(0)
}
for (let i = 0; i < 5; i++) {
    B.push(1)
}

console.log('A:', A)
console.log('B:', B)
```

If I run the code within a test with `yarn test` (i.e. `tsdx test`), everything is fine and the output is:
```bash
A: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1 ]
B: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1 ]
```

If I build the library and import it in node, though, I get something different:
```bash
A: [ <15 empty items> ]
B: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1 ]
```

### Expected behavior

I'd expect the built library imported in node to behave as it does in the tests:
```bash
A: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1 ]
B: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1 ]
```

### Additional context

- I tried to build the reported code (put in a single file) with _tsc_ and it works just fine (`tsc test.ts` and then `node test.js`)
- I use the spread operator in other parts of the project (yet with a simpler syntax, e.g. `arr3 = [...arr1, ...arr2]`) and it works

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.13.0
| TypeScript       | 3.8.3
| Browser          | -
| npm/Yarn         | Yarn
| Node             | v10.15.0
| Operating System | macOS 10.14.6

**Comment by agilgur5** [comment]
I'll have to look into it later, but it sounds like this might be related to TypeScript's `downlevelIteration`, for which there's this issue: https://github.com/jaredpalmer/tsdx/issues/376 .
That should behave the same between `tsc` and `tsdx` though 🤔

**Comment by ndrbrt** [comment]
Yes thank you, I did see #376, even though actually I solved my own issue by just using "option B".

I opened this one though, because, as you pointed out, I find strange the inconsistency between `tsc` and `tsdx`

**Comment by agilgur5** [comment]
I think it might be that the `tsconfig` `target` matters to TS for this transform; per [the docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options), it sounds like it only works when targeting ES5 or below. 

TSDX ignores your setting and forces `target` to `ESNext` and transpiles the rest down with `@babel/preset-env`, so that's probably the difference unless you're not using `target`?

Per https://github.com/jaredpalmer/tsdx/issues/376#issuecomment-566750042, it sounds like adding `@babel/preset-env` with `loose: false` to your `babelrc` should make it transpile down
