### ISSUE TITLE
Custom jest.setup.js

### ISSUE THREAD

**Issue by leandrotk** [jaredpalmer/tsdx#695]
I'm trying TSDX with React. And as I'm using `toBeInTheDocument` function from `@testing-library/jest-dom`, I need to import it in my test file.

But it would be awesome to add this import statement in the jest setup configuration instead of all test files I create.

Are there any way to TSDX read the "custom" jest.setup.js?

Thanks in advance!

**Comment by Oreoz** [comment]
I don't know if that's the prescribed way to do it, but I simply added two files to my root directory and it works like a charm.

```js
// jest.config.js
module.exports = {
  verbose: true,
  setupFilesAfterEnv: ["./setupTests.ts"],
};
```

```ts
// setupTests.ts
import "@testing-library/jest-dom";
```

**Comment by leandrotk** [comment]
Thanks, @Oreoz! It really works like a charm.

**Comment by agilgur5** [comment]
Yes, you can use `pacakge.json.jest` or `jest.config.js` to further configure Jest; it'll be shallow-merged with TSDX's built-in config.

`jest.config.js` has been supported since #229 -- this is actually a duplicate of #100. Please search the issues before reporting one.

Have a [TODO to add some more docs around this](https://github.com/jaredpalmer/tsdx/issues/692#issuecomment-616916364) as this isn't as explicit as it can be in the docs, but `tsdx test` is just a small wrapper around Jest.
