### ISSUE TITLE
Jest: MutationObserver is not a constructor

### ISSUE THREAD

**Issue by jantimon** [jaredpalmer/tsdx#724]
Can we please upgrade jest to fix this problem?
https://github.com/testing-library/react-testing-library/issues/662

**Comment by agilgur5** [comment]
As that issue says, you need to supply some polyfill or configure JSDOM. You can already do that in [Jest 24](https://jestjs.io/docs/en/24.x/configuration#testenvironment-string). I do not know what versions of JSDOM support MutationObserver, but if you want to use JSDOM 16, you can install and configure [`jest-environment-jsdom-sixteen`](https://github.com/SimenB/jest-environment-jsdom-sixteen) per the docs.

A breaking upgrade for Jest 25 and a few other deps is already slated for [v0.14](https://github.com/jaredpalmer/tsdx/milestone/2) and there is already [a PR for it](https://github.com/jaredpalmer/tsdx/pull/679). Jest 25 uses JSDOM 15 by default however, not 16, so I do not know if that supports your use case or not.
Jest 26 is still very recent and support is TBD because it also required TS 3.8 which [breaks a number of dependencies](https://github.com/jaredpalmer/tsdx/pull/679#issuecomment-631478298)
