### ISSUE TITLE
Quick Question on Private Distribution

### ISSUE THREAD

**Issue by neilchaudhuri** [jaredpalmer/tsdx#738]
First off, TSDX is great. Thank you all for open sourcing this.

I am building a React component library that needs to be published on a private Nexus NPM repo rather than actual NPM. So I need to be able to generate the tarball but push to a dedicated location besides NPM.

How can I configure TSDX to do this?

**Comment by jaredpalmer** [comment]
I think you can just add a script after build to zip the dist directory?

**Comment by neilchaudhuri** [comment]
Oh so just a `yarn pack` after build? Sounds good to me. Thanks.

**Comment by agilgur5** [comment]
@neilchaudhuri TSDX does not currently touch your publish process at all, so this question is out-of-scope. I would recommend searching your question online because there are plenty of results, even plenty Nexus-specific -- [here is one](https://gist.github.com/shirakaba/d4bc52330aecc2fcb20d15a29b2927e1). 

You don't need to generate a tarball and send it to some API, you can just set your [`publishConfig.registry`](https://docs.npmjs.com/using-npm/registry.html#i-dont-want-my-package-published-in-the-official-registry-its-private) in `package.json` as well as create an [`.npmrc`](https://docs.npmjs.com/files/npmrc) so that you publish to a different registry. Nexus supports this format.

**Comment by neilchaudhuri** [comment]
I appreciate the feedback. Thanks.

**Comment by Jucian0** [comment]
I've the same issue, I can't publish in private repository, when I run `npm publish` comand igone my private repository config and  try to publish my package on npm
